# Getting Started

This is the first session for the NEAD course!

`r paste(lorem::ipsum(sentences = 3))`

## Introduction to session 1 {-}

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("VEjOWxTw-v0&list", width = 475, height = 275) %>% use_start_time("0m04s")`

### Making an anchor {-}

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("8zp2yICvLvs", width = 475, height = 275) %>% use_start_time("0m0s")`

## What is NEAD? {-}

People with Non-Epileptic Attack Disorder (NEAD) experience episodes of temporary loss of control. During a NEAD episode people can experience symptoms that affect movement (e.g. shaking or falling) as well as changes to their senses (e.g. hearing, vision, taste and smell). Symptoms can also affect awareness (such as feeling confused, being unresponsive or blacking out). NEAD is a natural response to danger and is not an indication that something is medically wrong or that there is damage to the brain or nervous system. Different people experience different symptoms and NEAD symptoms often change over time.

Like many conditions, there are multiple terms used to describe the same experience. Some of the terms that you may have heard: Psychogenic seizures, 
Psychogenic non-epileptic seizures (PNES), Dissociative seizures, Conversion disorder, Functional seizures and Psychological seizures.

Approximately 20,000 people in the UK have this diagnosis – but it could be more. 1 out of every 5 people who see a doctor because of seizures go on to have a diagnosis of NEAD.

`r embed_youtube("i8Dlr22bmSM", width = 475, height = 275) %>% use_start_time("0m0s")`

## Ground Exercises {-}

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("MR36OORCM8c", width = 475, height = 275) %>% use_start_time("0m0s")`

# The traffic light system {-}
### Amber {-}

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("TgN1qXsvShU", width = 475, height = 275) %>% use_start_time("0m0s")`

### Red {-}

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("DdOZg9-8rdE", width = 475, height = 275) %>% use_start_time("0m0s")`

### Green {-}

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("Fy9IH0bnAx8", width = 475, height = 275) %>% use_start_time("0m0s")`

### Noticing {-}

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("gVNSWk0Xsm4", width = 475, height = 275) %>% use_start_time("0m0s")`

# Session one Homework {-}

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("oz97p0y5MeA", width = 475, height = 275) %>% use_start_time("0m0s")`

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("BX0D-8FBqMM", width = 475, height = 275) %>% use_start_time("0m0s")`

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("hVc5rqY6wzg", width = 475, height = 275) %>% use_start_time("0m0s")`

`r paste(lorem::ipsum(sentences = 3))`

`r embed_youtube("zVIOWVfTs", width = 475, height = 275) %>% use_start_time("0m0s")`

```{r, echo=F, include = F}
downloadthis::download_file(
  path = "files/session-1.pdf",
  output_name = "Session 1 Handout",
  button_label = "Session 1 Handout",
  button_type = "danger",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)
```

